accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<int:user_pk>/follow/', views.follow, name='follow'),    
    path('profile/update/', views.profile_update, name='profile_update'),    
    path('password/', views.password_change, name='password_change'),    
    path('delete/', views.delete, name='delete'),    
    path('edit/', views.edit, name='edit'),    
    path('logout/', views.logout, name='logout'),    
    path('login/', views.login, name='login'),    
    path('signup/', views.signup, name='signup'),    
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
urlpatterns = [
    
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('<str:username>/', accounts_views.people, name='people'),
    
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=10, blank=True)
    introduction = models.TextField(blank=True)
    
    def __str__(self):
        return self.nickname
        
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

posts/models.py
from django.db import models    # 장고모델 임포트
from django.conf import settings # 모델에 user를 추가하며 생긴 settings
from imagekit.models import ProcessedImageField #이미지 업로드
from imagekit.processors import ResizeToFill #이미지 수정

# Create your models here.
class Hashtag(models.Model):
    content = models.TextField(unique=True)
    
    def __str__(self):
        return self.content
    

class Post(models.Model): # Post라는 모델을 생성
    content = models.TextField() 
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts', blank=True) # 컬럼을 만들어 지는것이 아니다!!!
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 권한설정을 위한 외래키,
    hashtags = models.ManyToManyField(Hashtag, blank=True) # 역참조가 필요 없다는데 왜 필요없지?.. 위에 like_posts와 비교해보기
    def __str__(self):
        return self.content
        
class Image(models.Model):       #사진올리기위해 이미지 모델을 만든다
    post = models.ForeignKey(Post, on_delete=models.CASCADE)   # Post가 부모객체, 
    file = ProcessedImageField(
                blank=True,    # 빈값도 가능함,
                upload_to='posts/images',	 #이미지를 업로드하면 해당ㄹ경로로
                processors=[ResizeToFill(600, 600)],		#자르기
                format='JPEG',								#포맷
                options={'quality': 90},					#퀄리디설정
    )
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 우리가 만든게 아니라 정해진 단어를 써야함
    post = models.ForeignKey(Post, on_delete=models.CASCADE) # 우리가 만든 모델이라서 Post만 쓰면 된다
    content = models.CharField(max_length=140)
    
    def __str__(self):
        return self.content

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from .models import Profile

class UserCustomChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name',]

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'nickname', 'introduction',
        ]

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta): # Meta class도 상속받ㅇ르 수 있다
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .forms import *

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:list') # 로그인 한 상태에서 회원가입 누르면 인덱스로 리턴!!!
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)    # 프로필 추가
            auth_login(request, user)
            return redirect('posts:list')
    else:
        form = CustomUserCreationForm()
    ctx = {
        'form': form,
    }
    return render(request, 'accounts/form.html', ctx) # signup.html로 가도 된다
    
def login(request):
    if request.user.is_authenticated:
        return redirect('posts:list')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'posts:list')
    else:
        form = AuthenticationForm()
        next_url = request.GET.get('next', '')
    ctx = {
        'form': form,
        'next': next_url,
    }
    return render(request, 'accounts/form.html', ctx)

@require_POST
@login_required
def logout(request):
    auth_logout(request)
    return redirect('posts:list')

def people(request, username):
    people = get_object_or_404(get_user_model(), username=username)
    context = {
        'people':people,
        }
    return render(request, 'accounts/people.html', context)

@login_required
def edit(request):
    if request.method == 'POST':
        form = UserCustomChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            # return redirect('posts:list')
            return redirect('people', request.user.username)  # 인자가 왜 필요한거지 ? 없어도 될거같은데
    else:
        form = UserCustomChangeForm(instance=request.user)
    ctx = {
        'form': form,
    }
    return render(request, 'accounts/form.html', ctx)
    
@require_POST
@login_required
def delete(request):
    user = request.user
    user.delete()
    return redirect('posts:list')

@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # 비번변경시 로그아웃 되지 않게 해주는 것, 인자가 요청과 객체
            return redirect('posts:list')
    else:
        form = PasswordChangeForm(request.user)
    ctx = {
        'form': form,
    }
    return render(request, 'accounts/form.html', ctx)

@login_required
def profile_update(request):
    profile = Profile.objects.get_or_create(user=request.user)  # 카카오로그인으로 하면, 로그인 절차를 무시하고 로그인하기때문에 
                                                                # 프로필을 생성하지 않는다. 따라서 프로필이 있으면 get하고 없으면 create한다
    if request.method=="POST":
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('people', request.user.username)
    else:
        profile_form = ProfileForm(instance=request.user.profile)
    context = {
        'profile_form': profile_form,
    }
    return render(request, 'accounts/profile_update.html', context)
        
@login_required
def follow(request, user_pk):
    people = get_object_or_404(get_user_model(), pk=user_pk)
    if request.user in people.followers.all():
        people.followers.remove(request.user)
    # people(팔로우 누르려고 하는 애)이 팔로우 하고 있는 모든 유저중에, 현재 접속유저가 있으면, 언팔
    else:
        people.followers.add(request.user)
    return redirect('people', people.username)
    # 아니면 팔로우

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block content %}
{% if request.resolver_match.url_name == 'login' %}

<h1>Login</h1>
{% elif request.resolver_match.url_name == 'signup' %}
<h1>Signup</h1>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="hidden" name="next" value="{{ next }}">
    <button type="submit" class="btn btn-primary">제출</button>
</form>
<a href="{% provider_login_url 'kakao' method='oauth2' %}" class="btn btn-warning">카카로오그인</a>
{% endblock %}

accounts/templates/accounts/people.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center">{{ people.username }}'s Profile</h1>
<a href="{% url 'accounts:profile_update' %}" class="badge badge-success">프로필 수정</a>
<div class="jumbotron jumbotron-fluid text-center mb-2 text-white bg-dark">
  <div class="container">
    <h1 class="display-4">{{ people.profile.nickname }}</h1>
    <p class="lead">{{ people.profile.introduction }}</p>
    <hr class="border-white my-4">
    <p class="lead">팔로잉:{{people.followings.count}}</p>
    <p class="lead">팔로워:{{people.followers.count}}</p>
    
    {% if user != people %}
        {% if user in people.followers.all %}
        <a href="{% url 'accounts:follow' people.pk %}" class="btn btn-outline-primary">UnFollow</a>
        {% else %}
        <a href="{% url 'accounts:follow' people.pk %}" class="btn btn-primary">Follow</a>
        {% endif %}    
    {% endif %}
  </div>
</div>
<h3 class="text-center">{{ people.username }}이 작성한 게시글</h3>

<div class="row">
    {% for post in people.post_set.all|dictsortreversed:"pk" %}
    <div class="col-4 my-2">
        <div class="card" style="width: 18rem;">
            <img src="{{ post.image_set.first.file.url }}" class="card-img-top" alt="{{ post.image_set.first.file }}">
            <div class="card-body">
                <h5 class="card-title">{{ post.content }}</h5>
                <p class="card-text">{{ post.like_users.count }}명이 좋아합니다.</p>
                <p class="card-text">{{ post.comment_set.count }}개의 댓글</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<hr>
<h3 class="text-center">{{ people.username }}이 작성한 댓글</h3>
<div class="row">
    {% for comment in people.comment_set.all|dictsortreversed:"pk" %}
    <div class="col-4 my-2">
        <div class="card">
            <div class="card-body">
            <blockquote class="blockquote text-center">
                <p class="mb-0">{{ comment.post }}</p>
                <footer class="blockquote-footer">{{ comment }}</footer>
            </blockquote>
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<h1>프로필수정</h1>


<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form profile_form %}
    {% buttons submit="수정" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock %}