accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('<int:user_pk>/follow/', views.follow, name='follow'),    
    path('profile/update/', views.profile_update, name='profile_update'),    
    path('password/', views.password_change, name='password_change'),    
    path('delete/', views.delete, name='delete'),    
    path('edit/', views.edit, name='edit'),    
    path('logout/', views.logout, name='logout'),    
    path('login/', views.login, name='login'),    
    path('signup/', views.signup, name='signup'),    
]

insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
urlpatterns = [
    
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('<str:username>/', accounts_views.people, name='people'),
    
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('explore/', views.explore, name='explore'),
    path('hashtag/<int:hash_pk>/', views.hashtag, name='hashtag'),
    path('<int:post_pk>/like/', views.like, name='like'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:post_pk>/comments', views.comments_create, name='comments_create'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('', views.list, name='list'),
    ]

posts/models.py
from django.db import models    # 장고모델 임포트
from django.conf import settings # 모델에 user를 추가하며 생긴 settings
from imagekit.models import ProcessedImageField #이미지 업로드
from imagekit.processors import ResizeToFill #이미지 수정

# Create your models here.
class Hashtag(models.Model):
    content = models.TextField(unique=True)
    
    def __str__(self):
        return self.content
    

class Post(models.Model): # Post라는 모델을 생성
    content = models.TextField() 
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts', blank=True) # 컬럼을 만들어 지는것이 아니다!!!
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 권한설정을 위한 외래키,
    hashtags = models.ManyToManyField(Hashtag, blank=True) # 역참조가 필요 없다는데 왜 필요없지?.. 위에 like_posts와 비교해보기
    def __str__(self):
        return self.content
        
class Image(models.Model):       #사진올리기위해 이미지 모델을 만든다
    post = models.ForeignKey(Post, on_delete=models.CASCADE)   # Post가 부모객체, 
    file = ProcessedImageField(
                blank=True,    # 빈값도 가능함,
                upload_to='posts/images',	 #이미지를 업로드하면 해당ㄹ경로로
                processors=[ResizeToFill(600, 600)],		#자르기
                format='JPEG',								#포맷
                options={'quality': 90},					#퀄리디설정
    )
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 우리가 만든게 아니라 정해진 단어를 써야함
    post = models.ForeignKey(Post, on_delete=models.CASCADE) # 우리가 만든 모델이라서 Post만 쓰면 된다
    content = models.CharField(max_length=140)
    
    def __str__(self):
        return self.content

posts/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from itertools import chain
from .form import PostForm, ImageForm, CommentForm
from .models import Post, Comment, Image, Hashtag

@login_required
def create(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            post = post_form.save(commit=False)  # 권한에 ㄸㅏ라 수정삭제 버튼 없앨때 False를 추가
            post.user = request.user
            post.save()
            # hashtag - post.save()가 된 이후에 해시태그 코드가 와야함.
            # 1 게시글을 순회하면서 띄어쓰기를 잘라야 함
            for word in post.content.split():
                # 2 자른 단어가 #으로 시작하는지를 파악해야함
                if word[0] =='#':
                # if word.startswith('#'): #이것도 같다
                    hashtag = Hashtag.objects.get_or_create(content=word) 
                    #Hashtag(모델객체)의 인스턴스와 boolean을 return
                    # 3 이 해시태그가 기존 해시태그에 있는건지?
                    post.hashtags.add(hashtag[0])
            
            for image in request.FILES.getlist('file'):
                request.FILES['file'] = image
                image_form = ImageForm(files=request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False)
                    image.post = post
                    image.save()
            return redirect('posts:list')
    else:
        post_form = PostForm()
        image_form = ImageForm()
    context = {
        'post_form': post_form,
        'image_form': image_form,
    }
    return render(request, 'posts/form.html', context)
@login_required
def list(request):
    ########### 1 #############
    followings=request.user.followings.all()
    posts = Post.objects.filter(Q(user__in=followings) | Q(user=request.user.id)).order_by('-pk')
    
    ############# 2 ###########
    # followings = request.user.followings.all()
    # chain_followings = chain(followings, [request.user])
    
    # posts = Post.objects.filter(user__in=chain_followings).order_by('-pk')
    # posts = Post.objects.filter(user__in=request.user.followings.all()).order_by('-pk')
    comment_form = CommentForm()         #댓글 작성하기 위한 form 정의를 해야 인덱스에서 폼이 보임
    context = {'posts': posts,
        'form':comment_form
    }
    return render(request, 'posts/list.html', context)

def detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    ctx = {
        'post': post,
    }
    return render(request, 'posts/detail.html', ctx)

@login_required
def update(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    
    ######### 권한이 없는데 수정,삭제를 url에 입력한다면################
    if post.user != request.user:
        return redirect('posts:list')
    ######### 권한이 없는데 수정,삭제를 url에 입력한다면################
    
    
    if request.method == 'POST':
        post_form = PostForm(request.POST, instance=post)
        if post_form.is_valid():
            post = post_form.save()
            #hash tag update
            # 1 게시글을 순회하면서 띄어쓰기를 잘라야 함
            post.hashtags.clear()
            for word in post.content.split():
                if word[0] =='#':
                    hashtag = Hashtag.objects.get_or_create(content=word) 
                    #Hashtag(모델객체)의 인스턴스와 boolean을 return
                    # 3 이 해시태그가 기존 해시태그에 있는건지?
                    post.hashtags.add(hashtag[0])
            return redirect('posts:list')
    else:
        post_form = PostForm(instance=post)
    ctx = {
        'post_form': post_form,
    }
    return render(request, 'posts/form.html', ctx)

@require_POST
@login_required
def delete(request, post_pk):
    
    post = get_object_or_404(Post, pk=post_pk)
    ######### 권한이 없는데 수정,삭제를 url에 입력한다면################
    if post.user != request.user:
        return redirect('posts:list')
    ######### 권한이 없는데 수정,삭제를 url에 입력한다면################
    post.delete()
    return redirect('posts:list')

@require_POST
@login_required
def comments_create(request, post_pk): # 여기 post는 어디서 오는걸까
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user # 객체를 가져옴
        comment.post_id = post_pk # 객체로 가져오면 커리문이 한번 더 돌기때문에 바로 키를 가져옴?
        comment.save()
    return redirect('posts:list')

@require_POST
@login_required
def comments_delete(request, post_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user:
        comment.delete()    
    return redirect(f'/posts/#{post_pk}')

@login_required
def like(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    
    ####### 1번 방법 ################
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    return redirect('posts:list')
    ##### 2번방법#####################
    # user = request.user
    # if post.like_users.filter(pk=user.pk).exists():
    #     post.like_users.remove()

def explore(request):
    posts = Post.objects.order_by('-pk')
    # posts = Post.objects.exclude(user=request.user).order_by('-pk')
    
    comment_form = CommentForm()
    context = {
        'posts':posts,
        'form':comment_form,
    }
    return render(request, 'posts/explore.html', context)

def hashtag(request, hash_pk):
    hashtag = get_object_or_404(Hashtag, pk=hash_pk)
    posts = hashtag.post_set.order_by('-pk')
    context = {
        'hashtag':hashtag,
        'posts':posts,
    }
    return render(request, 'posts/hashtag.html', context)

posts/templates/posts/_nav.html
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark px-5">
    <a class="navbar-brand" href="{% url 'posts:list' %}">
        <i class="fab fa-instagram"> | Instagram</i>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
        <div></div>
        <div class="navbar-nav">
            
            <li class="nav-item">
                <span class="nav-text text-light"> {{user.username }}님 반갑습니다.</span>
            </li>
        </div>
        <div class="navbar-nav">
            <li class="nav-item">
                <a href="{% url 'posts:explore' %}" class="nav-link">EXPLORE</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'posts:create' %}" class="nav-link">New</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a href="{% url 'people' user.username %}" class="nav-link">MyPage</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'accounts:edit' %}" class="nav-link">회원정보수정</a>
            </li>
            <!-- <li class="nav-item">-->
            <!--    <a href="{# url 'accounts:logout' #}" class="nav-link">로그아웃</a>-->
            <!--</li>-->
            <!-- <li class="nav-item">-->
            <!--    <a href="{# url 'accounts:delete' #}" class="nav-link">회원탈퇴</a>-->
            <!--</li>-->
            <form class="nav-item" action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <button class="nav-link btn btn-info" type="submit">Logout</button>
            </form>
            <form class="nav-item" action="{% url 'accounts:delete' %}" method="POST" onsubmit="return confirm('정 말탈 퇴?');">
                {% csrf_token %}
                <button class="nav-link btn btn-danger" type="submit">탈퇴</button>
            </form>
            {% else %}
            <li class="nav-item">
                <a href="{% url 'accounts:signup' %}" class="nav-link">SignUp</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'accounts:login' %}" class="nav-link">Login</a>
            </li>
            {% endif %}
        </div>
    </div>
</nav>

posts/templates/posts/_post.html
{% load bootstrap4 %}
{% load posts_templatetag %}
{% load 
<div class="col-5 my-3">
    <div id="{{ post.id }}"class="card">    <!-- 여기 나오는 모든 post는 list에서 posts를 for문으로 돌리는 변수 post이다-->
                            <!--list.html에서 for문 변수명을 test로 바꾸고 여기 모든 post를 test로 바꿔도 동작한다.-->
    <div class="card-header">
         <h5 class="card-text"><a class="card-link" href="{% url 'people' post.user.username %}">{{ post.user }}</a></h5>
    </div>
        {% if post.image_set %}
        <div id="post{{post.pk}}" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                {% for image in post.image_set.all %}
                <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                    <img src="{{ image.file.url }}" class="d-block w-100" alt="{{ image.file }}">
                </div>
                {% endfor %}
            
            <a class="carousel-control-prev" href="#post{{post.pk}}" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#post{{post.pk}}" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            </div>
        </div>
        {% else %}
        <img src="{{ image.file.url }}" class="card-img-top" alt="NMG">
        {% endif %}
        <div class="card-body">
            <a href="{% url 'posts:like' post.pk %}" class="card-link">
                {{ post.like_users.count }}
                {% if user in post.like_users.all %}
                    <i class="fas fa-heart fa-lg" style="color:crimson"></i>
                {% else %}
                    <i class="fas fa-heart fa-lg" style="color:black"></i>
                {% endif %}
                
            </a>
            <h5 class="card-text">
                <a href="{% url 'posts:detail' post.id %}">{{ post.content }}</a>
            </h5>
            <br>
            {% if request.user == post.user %}
            <a href="{% url 'posts:update' post.pk %}" class="btn btn-warning">[EDIT] </a>
            <!-- 의문1 post.pk와 post_pk는 무슨차이일까?-->
            <!-- 내생각 : post.pk는 post클래스 안의 속성 pk이고
                          post_pk(url이나 뷰함수에 있는것)은 들어오는 정수형변수의 이름이다.
                          즉 post_pk는 아무렇게나 써도 되는 이름이고 post.pk는 클래스의 정해진 속성이다.-->
            <form action="{% url 'posts:delete' post.pk %}" method="POST" onsubmit="return confirm('R e a l l y ?');" style="display:inline">
                {% csrf_token %}
                <input type="submit" value="[DELETE]" class="btn btn-danger" />
            </form>
            {% endif %}
        </div>
        
        
        <div class="card-footer">
            {% if user.is_authenticated %}
            <form class="d-flex align-items-start justify-content-around" 
                action="{% url 'posts:comments_create' post.id %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-primary" type="submit">댓글</button>
            </form>
            {% else %}
            <a href="{% url 'accounts:login' %}">댓글달려면 로그인하세요</a>
            
            {% endif %}
            <hr>
            {% for comment in post.comment_set.all %}
                <div class="d-flex align-items-center m-3">
                    <span style="font-weight: bold;">{{ comment.user }}</span>&nbsp;/&nbsp;{{ comment.content }}
                    {% if comment.user == user %}
                    <form class="mx-2" action="{% url 'posts:comments_delete' post.id comment.id %}" method="post">
                        {% csrf_token %}
                        <button class="border-0" type="submit"><i class="fas fa-times"></i></button>
                    </form>
                    {% endif %}
                </div>
            
            {% endfor %}
        </div>
    </div>
</div>

posts/templates/posts/detail.html
{% block content %}
{% load posts_templatetag %}
<p>{{ post.id }} / {{ post|hashtag_link|safe  }}</p>
<div>
<a href="{% url 'posts:update' post.id %}">UPDATE</a>
<form action="{% url 'posts:delete' post.id %}" method="POST">
    {% csrf_token %}
    <button type="submit">삭제</button>
</form>
<a href="{% url 'posts:list' %}">BACK</a>
</div>
{% endblock %}

posts/templates/posts/explore.html
{% extends 'base.html' %}
{% block content %}

<h1>LIST</h1>
<div class="d-inline-flex flex-wrap justify-content-center">

{% for post in posts %}  <!-- post는 내가 정하는것.. 이 변수가 _post로 간다-->
    {% include 'posts/_post.html' %}
{% endfor %}
</div>
{% endblock %}

posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
                                                        <!--메인(list.html)에서 글작성을 눌렀을 때, 이 form.html페이지가 뜬다.  -->
{% if request.resolver_match.url_name == 'create' %} <!-- 똑같은 창인데 url명이 create면, NEW가 뜨고 -->
<h1>NEW</h1>
{% else %}                                            <!-- 아니면 EDIT라고 뜸. -->
                                        <!-- 뷰함수 update와 create 두개가 다 form.html로 render하기 때문에 분기를 나눔 -->
<h1> EDIT </h1>
{% endif %}
<form action="" method="POST" enctype="multipart/form-data"> <!--multipart가 없어도 여러장 선택이 된다. 이 역할은 뭘까? 
                                                                                     = > 이미지 올릴때 필요하다.-->
    {% csrf_token %}                                          <!--action이 자신이면 submit하면 자신의링크(views.py에서 정의된)로 보낸다 -->
    {% bootstrap_form post_form %}                             <!-- action이 자기자신이 아니라 url posts:list면 저장이안된다. 왜지.
                                                                A: 그러면 list로 보내는게 아니라 list url로 이동하는기에 view함수 create로 들어가는게 아니라
                                                                 list로 들어간다. 즉, 홈버튼과 같아짐.-->
    {% if image_form %}
        {% bootstrap_form image_form show_label=False %}
    {% endif %}
    <button type="submit" class="btn btn-primary"> SUBMIT</button>
    <button type="reset" class="btn btn-outline-primary"> Cancel</button>
    <a href="{% url 'posts:list' %}" class='btn btn-info'>BACK</a>
</form>

{% endblock %}

posts/templates/posts/hashtag.html
{% extends 'base.html' %}
{% block content %}
<h1 class="text-center">{{ hashtag_content }}</h1>
<div class="jumbotron jumbotron-fluid text-center mb-2 text-white bg-dark">
  <div class="container">
    <h1 class="display-4">총 {{ hashtag.post_set.count }}개의 태그</h1>
    <hr class="border-white my-4">
    
  </div>
  <hr>
  <h3>{{ hashtag_content }}를 태그한 글</h3>
 </div>
<div class="row">
    {% for post in posts %}
    <div class="col-4 my-2">
        <div class="card" >
            <img src="{{ post.image_set.first.file.url }}" class="card-img-top" alt="{{ post.image_set.first.file }}">
            <div class="card-body">
                <h5 class="card-title">{{ post.content }}</h5>
                <p class="card-text">{{ post.like_users.count }}명이 좋아합니다.</p>
                <p class="card-text">{{ post.comment_set.count }}개의 댓글</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{% if user.is_authenticated %}
<a href="{% url 'posts:create' %}" class="btn btn-primary justify-content-end" >글작성</a>
{% else %}
<a href="{% url 'accounts:signup' %}" class="btn btn-primary ">회원가입</a>
{% endif %}
<h1>LIST</h1>
<div class="d-inline-flex flex-wrap justify-content-center">

{% for post in posts %}  <!-- post는 내가 정하는것.. 이 변수가 _post로 간다-->
    {% include 'posts/_post.html' %}
{% endfor %}
</div>
{% endblock %}